import { Card, CardContent } from "@/components/ui/card";
import { Link, useLocation } from "wouter";
import { AlertTriangleIcon } from "lucide-react";
import { NavigationMenu } from "../components/navigation-menu";
import { SmartBackButton } from "../components/smart-back-button";
import { motion } from "framer-motion";

export default function Policy() {
  const [location] = useLocation();
  
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 w-full z-50 border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="max-w-6xl mx-auto px-6 md:px-8 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center space-x-3 hover:opacity-80 transition-opacity">
              <div className="w-0 h-0 border-l-[8px] border-r-[8px] border-b-[14px] border-l-transparent border-r-transparent border-b-foreground"></div>
              <span className="text-lg font-medium text-foreground">Coin Feedly</span>
            </Link>
            
            <NavigationMenu currentPath={location} />
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 md:px-8 py-12 md:py-20">
        <SmartBackButton className="mb-12" />
          
          <motion.article 
            className="space-y-12"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            <header className="space-y-6">
              <h1 className="text-4xl md:text-6xl font-semibold text-foreground leading-tight tracking-tight">
                Terms & Privacy Policy
              </h1>
              <p className="text-xl md:text-2xl text-muted-foreground leading-relaxed">
                Simple terms and privacy information
              </p>
            </header>

            {/* Important Disclaimer */}
            <Card className="bg-amber-50 dark:bg-amber-950/20 border-amber-200 dark:border-amber-800">
              <CardContent className="p-8">
                <div className="flex items-start space-x-4">
                  <AlertTriangleIcon className="h-8 w-8 text-amber-600 dark:text-amber-400 mt-1 flex-shrink-0" />
                  <div className="space-y-3">
                    <h3 className="text-xl font-semibold text-amber-900 dark:text-amber-100">
                      Important Disclaimer
                    </h3>
                    <p className="text-amber-800 dark:text-amber-200 text-lg leading-relaxed">
                      AI predictions are not financial advice. Always conduct your own research and consult financial professionals before making investment decisions.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="space-y-12">
              <Card className="bg-background/50 border-border/30 hover:bg-background/80 transition-colors duration-300">
                <CardContent className="p-10 space-y-8">
                  <h2 className="text-3xl font-semibold text-foreground">Privacy & Data</h2>
                  
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-xl font-semibold text-foreground mb-3">No Personal Data Collection</h3>
                      <p className="text-muted-foreground leading-relaxed">
                        We don't collect, store, or process any personal information. No account creation, emails, or registration required.
                      </p>
                    </div>

                    <div>
                      <h3 className="text-xl font-semibold text-foreground mb-3">Market Data Sources</h3>
                      <p className="text-muted-foreground leading-relaxed">
                        All cryptocurrency prices come from reliable market data providers including CoinGecko API. AI predictions are generated by Claude, ChatGPT, and Deepseek models.
                      </p>
                    </div>

                    <div>
                      <h3 className="text-xl font-semibold text-foreground mb-3">Cookies</h3>
                      <p className="text-muted-foreground leading-relaxed">
                        We only use essential technical cookies for website functionality. No tracking or analytics cookies.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card className="bg-background/50 border-border/30 hover:bg-background/80 transition-colors duration-300">
                <CardContent className="p-10 space-y-8">
                  <h2 className="text-3xl font-semibold text-foreground">Terms of Use</h2>
                  
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-xl font-semibold text-foreground mb-3">Platform Purpose</h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Coin Feedly is for educational and informational purposes only. We track AI model performance on cryptocurrency predictions.
                      </p>
                    </div>

                    <div>
                      <h3 className="text-xl font-semibold text-foreground mb-3">Not Financial Advice</h3>
                      <p className="text-muted-foreground leading-relaxed">
                        AI predictions are experimental and may be wrong. Always do your own research and consult financial professionals before investing.
                      </p>
                    </div>

                    <div>
                      <h3 className="text-xl font-semibold text-foreground mb-3">Your Responsibility</h3>
                      <p className="text-muted-foreground leading-relaxed">
                        You're responsible for your own investment decisions. Never invest more than you can afford to lose.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </motion.article>
      </main>

      {/* Modern Footer */}
      <footer className="relative z-10 border-t border-border/30 mt-20 md:mt-32">
        <div className="max-w-7xl mx-auto px-6 md:px-8 py-12 md:py-20">
          <motion.div 
            className="text-center space-y-8"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <div className="flex items-center justify-center space-x-3">
              <div className="w-0 h-0 border-l-[8px] border-r-[8px] border-b-[14px] border-l-transparent border-r-transparent border-b-foreground"></div>
              <span className="font-semibold text-foreground">Coin Feedly</span>
            </div>
            <div className="text-sm text-muted-foreground space-y-2">
              <p>© 2025 Coin Feedly</p>
              <p className="text-xs">Loremt ApS CVR-nr 41691360</p>
            </div>
          </motion.div>
        </div>
      </footer>
    </div>
  );
}